---
language: node_js

node_js:
  - '0.10'
  - '0.11'

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
